-- Step 1C: Insert 100 Test Names into scraper_db
-- Run this SQL script in your MySQL database

USE scraper_db;

INSERT INTO tests (test_name, is_active) VALUES
('Complete Blood Count (CBC)', true),
('Hemoglobin (Hb)', true),
('Blood Group ABO & Rh Typing', true),
('Blood Glucose Fasting', true),
('Blood Glucose Post Prandial', true),
('HbA1c', true),
('Lipid Profile', true),
('Liver Function Test (LFT)', true),
('Kidney Function Test (KFT)', true),
('Serum Creatinine', true),
('Blood Urea (BUN)', true),
('Serum Electrolytes', true),
('Urine Routine & Microscopy', true),
('Urine Albumin', true),
('Albumin Creatinine Ratio (ACR)', true),
('Thyroid Profile (T3, T4, TSH)', true),
('TSH', true),
('Free T3', true),
('Free T4', true),
('Vitamin D (25-OH)', true),
('Vitamin B12', true),
('Serum Calcium', true),
('Serum Phosphorus', true),
('Serum Magnesium', true),
('Iron Studies', true),
('Serum Ferritin', true),
('C-Reactive Protein (CRP)', true),
('ESR (Erythrocyte Sedimentation Rate)', true),
('Prothrombin Time (PT/INR)', true),
('APPT', true),
('Dengue IgG & IgM', true),
('Malaria Antigen Test', true),
('Widal Test', true),
('Hepatitis B Surface Antigen (HBsAg)', true),
('Anti-HCV Antibody', true),
('HIV 1 & 2 Antibody', true),
('Urine Pregnancy Test', true),
('Beta-HCG', true),
('PSA (Prostate Specific Antigen)', true),
('AFP (Alpha Fetoprotein)', true),
('CEA (Carcinoembryonic Antigen)', true),
('CA-125', true),
('CA-19-9', true),
('Troponin-I', true),
('CK-MB', true),
('BNP (B-Type Natriuretic Peptide)', true),
('ECG', true),
('2D Echocardiography', true),
('Chest X-Ray', true),
('Ultrasound Whole Abdomen', true),
('Ultrasound Pelvis', true),
('Ultrasound Pregnancy', true),
('CT Scan Brain', true),
('MRI Brain', true),
('CT Scan Chest', true),
('CT Scan Abdomen', true),
('Mammography', true),
('DEXA Bone Mineral Density', true),
('Pap Smear', true),
('Stool Routine Examination', true),
('Stool Occult Blood', true),
('Blood Culture', true),
('Urine Culture & Sensitivity', true),
('AFB Smear (ZN Stain)', true),
('AFB GeneXpert (TB PCR)', true),
('Sputum Culture', true),
('COVID-19 RT-PCR', true),
('D-Dimer', true),
('Procalcitonin', true),
('ANA by IFA', true),
('Rheumatoid Factor (RF)', true),
('Anti-CCP Antibody', true),
('Uric Acid', true),
('Amylase', true),
('Lipase', true),
('Electrocardiogram Holter Monitoring', true),
('Pulmonary Function Test (PFT)', true),
('Allergy Screening Panel (Phadiatop)', true),
('Total IgE', true);

-- Verify insertion
SELECT COUNT(*) as total_tests FROM tests;
SELECT * FROM tests LIMIT 10;
